#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  untitled.py
#  
#  Copyright 2015  <pi@ece464raspi>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  

import RPi.GPIO as GPIO


def main():
	GPIO.setmode(GPIO.BOARD)
	GPIO.setup(18, GPIO.OUT)

	p = GPIO.PWM(18, 0.5)
	p.start(1)
	raw_input('Press return to stop:')   # use raw_input for Python 2
	p.stop()
	GPIO.cleanup()
	
	
	
	return 0

if __name__ == '__main__':
	main()

