#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  untitled.py
#  
#  Copyright 2015  <pi@ece464raspi>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  

from RPIO import PWM

def main():


	servo = PWM.Servo()

# Add servo pulse for GPIO 17 with 1200µs (1.2ms)
	#servo.set_servo(17, 1200)

# Add servo pulse for GPIO 17 with 2000µs (2.0ms)
	servo.set_servo(17, 2000)
	
	raw_input('Press return to stop:')   # use raw_input for Python 2

# Clear servo on GPIO17
	servo.stop_servo(17)
	return 0

if __name__ == '__main__':
	main()

